### PR TITLE
Ajust outputfile name such that it doesn't overwrite the template web…

### PR DESCRIPTION
**Pull request by kennethblite**
…stub.html file on run.

### CODE REVIEW

**Comment by BenGardiner** [comment]
I like the idea -- since it would support other workflows than my own. :)

Please make it conditional on a command-line flag though -- there are `generateme` scripts out there relying on the present behaviour.

**Comment by kennethblite** [comment]
I can add the command flag no problem, but do the scripts regenerate webstub.html each time at the end of their run?

**Comment by bengardiner-at-irdeto** [comment]
> but do the scripts regenerate webstub.html each time at the end of their run?

not sure (what that means)

**Comment by BenGardiner** [comment]
this was a good idea which we did implement in changes already merged into master

**Comment by kennethblite** [comment]
Sounds good.

**Pull request closed without merging**
